---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Determine Docker Compose download URL
  set_fact:
    docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ docker_compose_os }}-{{ docker_compose_arch }}"

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy Docker Compose file
  copy:
    src: /home/ian/Development2/code/Yolo/yolo/docker-compose.yml
    dest: /home/vagrant/docker-compose.yml
    remote_src: no


- name: Start backend Docker service
  command: docker-compose up -d backend
  args:
    chdir: /vagrant
  tags: backend